name: UUP Download Ubuntu

on:
  workflow_dispatch:
    inputs:
      file-name:
        description: 'upload the zip package to this repo.'
        required: true
        default: ''

jobs:
  Download:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Preparing for the environment
      run: |
        sudo apt-get install aria2 zip unzip cabextract wimtools chntpw genisoimage
    - name: Unzip
      run: |
        unzip ${{ github.event.inputs.file-name }}
    - name: run
      run: |
        sudo chmod 777 uup_download_linux.sh
        sudo bash uup_download_linux.sh
        ls -a
    - name: Upload
      uses: actions/upload-artifact@main
      with:
        name: ISO
        path: ./*.ISO
    - name: Zip and Upload to WeTransfer
      run: |
        mkdir isos
        zip -r iso.zip *.ISO
        zip -s 1g iso.zip --out ./isos/isos.zip 
        curl -sL https://git.io/file-transfer | sh 
        ./transfer wet -s ./isos/
        
        
        

        
        
